#!/usr/bin/python
# Author: Francisco Castello
# script: dhcpinfo.py
#     This scripts helps to parse the dhcpd.leases file
#     generated by isc-dhcp-server to make the output
#     more human readable
#  Tested with isc-dhcp-server 4.2.4


#
#Program Variables
#
DHCPLeasesFile="/var/lib/dhcp/dhcpd.leases"
dhcpinfo_version="0.2"


import os
import re

class DhcpLease:
    """
    DHCP lease class
    This class is used to store information 
    needed from each lease. This class can be
    extended with more information if we need 
    more parmeters.
    """
    IP = 0
    MAC = 0
    StartDate = 0
    EndDate = 0    
    State = 'Free'
    
    def __init__(self, ip , mac , SDate, EDate, state):
        """
        Class Constructor
        Feeds all information needed for the class
        Parameters
        ip: Lease's IP address
        mac: Lease's MAC address
        SDate: Lease's start date
        EDate: Lease's end date
        state: Lease's state
        """
         self.IP = ip
         self.MAC = mac
         self.StartDate = SDate
         self.EndDate = EDate
         self.State = state

    def PrintLease(self):
        """
        Method to print class information
        in a tabbed format
        """
        print("{}\t{}\t{}\t{}\t {}".format(self.IP,self.MAC,self.StartDate,self.EndDate,self.State))
    

    
class IscDhcpLeases:
    """
    Class to parse save and iterate leases from a file
    """
    #Lease File default /var/lib/dhcp/dhcpd.leases
    IscDhcpLeaseFile = "/var/lib/dhcp/dhcpd.leases"
    # List of all leases Current Leases
    IscDhcpLeases = []
    # List of all leases extracted in raw format from file
    IscDhcpLeasesRaw = []
    
    def __init__(self, DhcpLeaseFile):
        """
        Constructor 
        Parameters
        DhcpLeaseFile: isc dhcpd lease filename
        """
        command = 'cat {}'.format(DhcpLeaseFile)
        cmdText = os.popen(command).read()
        text = r"""%s""" % cmdText
        self.ParseLeases(text)

    def ParseLeases(self, leaseText):
        """
        Method to parse lease parameters from text
        """
        #Parse text to extract all blocks of leases into a list
        self.IscDhcpLeasesRaw = re.findall('lease [0-9]*.[0-9]*.[0-9]*.[0-9]* {.*?}',leaseText,re.DOTALL)

        #here we loop backwards because the file gets apended with updates and the newest
        #information is valid from bottom to top
        for LeaseRaw in reversed(self.IscDhcpLeasesRaw):
            # Get the IP from the lease
            IPraw = re.findall('lease ([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*) {',LeaseRaw,re.DOTALL)
            #find if the IP is already added to the CURRENT lease list and keep parsing
            #parameters. Otherwise if IP is already there do nothing.
            if not self.FindCurrentIp(IPraw[0]):
                #parse mac address
                MACraw = re.findall('hardware ethernet ([a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2});',LeaseRaw,re.DOTALL)
                #test if we got a mac address
                if not MACraw:
                    MAC=None
                else:
                    MAC=MACraw[0]
                #parse start date
                STARTraw = re.findall('starts [0-9] ([0-9]{4}\/[0-9]{2}\/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})',LeaseRaw,re.DOTALL)
                #parse end date
                ENDSraw = re.findall('ends [0-9] ([0-9]{4}\/[0-9]{2}\/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})',LeaseRaw,re.DOTALL)
                
                #che lease state
                if LeaseRaw.find("  binding state active;")!=-1:
                    STATEraw = 'Active'
                else:
                    if LeaseRaw.find("  binding state abandoned;")!=-1:
                        STATEraw = 'Abandoned'
                    else:
                        if LeaseRaw.find("  binding state free;")!=-1:
                            STATEraw = 'Free'
                #insert this lease into the current lease list
                self.IscDhcpLeases.append(DhcpLease(IPraw[0],MAC,STARTraw[0],ENDSraw[0],STATEraw))
        

    def FindCurrentIp(self, ip):
        """
        Method to find an IP address in current IscDhcpLeases list
        """
        for Lease in self.IscDhcpLeases:
            if Lease.IP == ip:
                return 1
        return 0
        
        

    def PrintCurrentLeases(self):
        """
        method to print all current leases
        """
        for Lease in reversed(sorted(self.IscDhcpLeases,key=lambda Lease: Lease.IP)):
            Lease.PrintLease()
    
    def PrintIscLeasesRaw(self):
        """
        method to print IscDhcpLeasesRaw this is for debugging
        """
        print self.IscDhcpLeasesRaw
                
    def GetCurrentFreeLeases(self):
        """
        Method to count all current free leases
        """
        freeLeaseCount = 0
        for Lease in self.IscDhcpLeases:
            if Lease.State == 'Free':
                freeLeaseCount = freeLeaseCount + 1
        return freeLeaseCount
            
    def GetCurrentActiveLeases(self):
        """
        Method to count all current Active leases
        """
        activeLeaseCount = 0
        for Lease in self.IscDhcpLeases:
            if Lease.State == 'Active':
                activeLeaseCount = activeLeaseCount + 1
        return activeLeaseCount

    def GetCurrentAbandonedLeases(self):
        """
        Method to count all current Abandoned leases
        """
        abandonedLeaseCount = 0
        for Lease in self.IscDhcpLeases:
            if Lease.State == 'Abandoned':
                abandonedLeaseCount = abandonedLeaseCount + 1
        return abandonedLeaseCount
                
                
                
                
print "Lease IP\t    MAC\t                     StartDate\t               EndDate"    
LEASE = IscDhcpLeases(DHCPLeasesFile)
LEASE.PrintCurrentLeases()
print LEASE.GetCurrentFreeLeases()
print LEASE.GetCurrentActiveLeases()
print LEASE.GetCurrentAbandonedLeases()


