#!/usr/bin/python
# Author: Francisco Castello
# script: dhcpinfo.py
#     This scripts helps to parse the dhcpd.leases file
#     generated by isc-dhcp-server to make the output
#     more human readable
#  Tested with isc-dhcp-server 4.2.4

import dhcpinfolib
#
#Program Variables
#
#DHCPLeasesFile="/var/lib/dhcp/dhcpd.leases"
DHCPLeasesFile="lease3"
dhcpinfo_version="0.3"


                
print "Lease IP\t    MAC\t                     StartDate\t               EndDate"    
LEASE = dhcpinfolib.IscDhcpLeases(DHCPLeasesFile)
LEASE.PrintCurrentLeases()
print("Free leases: {}".format(LEASE.GetCurrentFreeLeases()))
print("Active leases: {}".format(LEASE.GetCurrentActiveLeases()))
print("Abandoned leases: {}".format(LEASE.GetCurrentAbandonedLeases()))


